name: Hexo Deploy

on:
  push:
    branches: [ source ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 10.x
    uses: actions/setup-node@v1
    with:
        node-version: '10.x'
    - name: prepare build env
    env:
        GH_ACTION_DEPLOY_KEY: ${{secrets.ACTION}}
    run: |
        mkdir -p ~/.ssh/
        echo "$GH_ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        git config --global user.name 'hw93'
        git config --global user.email 'mechanicwei@qq.com'
        npm i -g hexo-cli
        npm i
    - name: deploy to github
    run: |
      hexo clean && hexo deploy